[
  {
    title: "SEO Consultation Service",
    description: "Expert SEO consultation for improving website rankings.",
    sellerEmail: "seo@example.com",
    orderQueue: [],
    category: "Digital Marketing",
    subCategory: "SEO",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/71bTZLx/9.png",
      "https://i.ibb.co/HXqVmB3/10.png",
      "https://i.ibb.co/S5YtBRD/2.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 299,
        description: "Basic SEO consultation package",
        deliveryTime: "7 days",
        features: ["Keyword Analysis", "On-Page SEO", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 599,
        description: "Standard SEO consultation package",
        deliveryTime: "14 days",
        features: [
          "Competitor Analysis",
          "On-Page and Off-Page SEO",
          "Premium Support",
        ],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 999,
        description: "Premium SEO consultation package",
        deliveryTime: "30 days",
        features: [
          "Comprehensive SEO Strategy",
          "Monthly Reporting",
          "Priority Support",
        ],
        revisionType: 3,
      },
    },
  },
  {
    title: "Social Media Management",
    description:
      "Professional social media management services for businesses.",
    sellerEmail: "social@example.com",
    orderQueue: [],
    category: "Digital Marketing",
    subCategory: "Social Media",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/0yH8QdX/6.png",
      "https://i.ibb.co/V3qcvh2/8.png",
      "https://i.ibb.co/KLjLKRt/4.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 199,
        description: "Basic social media management package",
        deliveryTime: "7 days",
        features: [
          "3 Social Media Platforms",
          "Content Posting",
          "Standard Support",
        ],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 399,
        description: "Standard social media management package",
        deliveryTime: "14 days",
        features: [
          "5 Social Media Platforms",
          "Content Creation",
          "Premium Support",
        ],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 799,
        description: "Premium social media management package",
        deliveryTime: "30 days",
        features: ["Customized Strategy", "Ads Management", "Priority Support"],
        revisionType: 3,
      },
    },
  },
  {
    title: "E-commerce Website Development",
    description: "Custom e-commerce website development services.",
    sellerEmail: "ecommerce@example.com",
    orderQueue: [],
    category: "Web Development",
    subCategory: "Front-End Development",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/xscDbbs/7.png",
      "https://i.ibb.co/PzJjWtH/3.png",
      "https://i.ibb.co/4mbNs0J/5.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 799,
        description: "Basic e-commerce website development package",
        deliveryTime: "14 days",
        features: [
          "Responsive Design",
          "Up to 50 Products",
          "Standard Support",
        ],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 1499,
        description: "Standard e-commerce website development package",
        deliveryTime: "30 days",
        features: [
          "Responsive Design",
          "Up to 500 Products",
          "Premium Support",
        ],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 2499,
        description: "Premium e-commerce website development package",
        deliveryTime: "45 days",
        features: ["Custom Features", "Unlimited Products", "Priority Support"],
        revisionType: 3,
      },
    },
  },
  {
    title: "Legal Consultation Service",
    description:
      "Expert legal consultation services for individuals and businesses.",
    sellerEmail: "legal@example.com",
    orderQueue: [],
    category: "Legal Services",
    subCategory: "General Legal",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/S5YtBRD/2.png",
      "https://i.ibb.co/PzJjWtH/3.png",
      "https://i.ibb.co/KLjLKRt/4.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 199,
        description: "Basic legal consultation package",
        deliveryTime: "7 days",
        features: ["30-Minute Consultation", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 349,
        description: "Standard legal consultation package",
        deliveryTime: "14 days",
        features: ["1-Hour Consultation", "Premium Support"],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 599,
        description: "Premium legal consultation package",
        deliveryTime: "21 days",
        features: ["2-Hour Consultation", "Priority Support"],
        revisionType: 3,
      },
    },
  },
  {
    title: "Photography Services",
    description: "Professional photography services for events and portraits.",
    sellerEmail: "photo@example.com",
    orderQueue: [],
    category: "Photography",
    subCategory: "Event Photography",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/V3qcvh2/8.png",
      "https://i.ibb.co/71bTZLx/9.png",
      "https://i.ibb.co/HXqVmB3/10.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 299,
        description: "Basic event photography package",
        deliveryTime: "1 day",
        features: ["2-Hour Coverage", "Standard Editing", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 499,
        description: "Standard event photography package",
        deliveryTime: "2 days",
        features: ["4-Hour Coverage", "Advanced Editing", "Premium Support"],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 799,
        description: "Premium event photography package",
        deliveryTime: "3 days",
        features: [
          "Full-Day Coverage",
          "Professional Editing",
          "Priority Support",
        ],
        revisionType: 3,
      },
    },
  },
  {
    title: "Logo Design Service",
    description: "Creative logo design solutions for businesses and brands.",
    sellerEmail: "logodesign@example.com",
    orderQueue: [],
    category: "Graphic Design",
    subCategory: "Logo Design",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/xscDbbs/7.png",
      "https://i.ibb.co/PzJjWtH/3.png",
      "https://i.ibb.co/V3qcvh2/8.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 199,
        description: "Basic logo design package",
        deliveryTime: "5 days",
        features: ["1 Logo Concept", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 349,
        description: "Standard logo design package",
        deliveryTime: "7 days",
        features: ["2 Logo Concepts", "Premium Support"],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 599,
        description: "Premium logo design package",
        deliveryTime: "10 days",
        features: ["3 Logo Concepts", "Priority Support"],
        revisionType: 3,
      },
    },
  },
  {
    title: "Content Writing Service",
    description:
      "High-quality content writing services for blogs and websites.",
    sellerEmail: "contentwriter@example.com",
    orderQueue: [],
    category: "Writing & Translation",
    subCategory: "Content Writing",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/4mbNs0J/5.png",
      "https://i.ibb.co/0yH8QdX/6.png",
      "https://i.ibb.co/xscDbbs/7.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 199,
        description: "Basic content writing package",
        deliveryTime: "7 days",
        features: ["500 Words", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 349,
        description: "Standard content writing package",
        deliveryTime: "14 days",
        features: ["1000 Words", "Premium Support"],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 599,
        description: "Premium content writing package",
        deliveryTime: "21 days",
        features: ["1500 Words", "Priority Support"],
        revisionType: 3,
      },
    },
  },
  {
    title: "Virtual Assistant Service",
    description: "Efficient virtual assistant services for business tasks.",
    sellerEmail: "va@example.com",
    orderQueue: [],
    category: "Administrative Support",
    subCategory: "Virtual Assistance",
    faqs: [],
    reviews: [],
    images: [
      "https://i.ibb.co/V3qcvh2/8.png",
      "https://i.ibb.co/71bTZLx/9.png",
      "https://i.ibb.co/HXqVmB3/10.png",
    ],
    packages: {
      basic: {
        name: "Basic Package",
        price: 199,
        description: "Basic virtual assistant package",
        deliveryTime: "7 days",
        features: ["10 Hours of Assistance", "Standard Support"],
        revisionType: 2,
      },
      standard: {
        name: "Standard Package",
        price: 349,
        description: "Standard virtual assistant package",
        deliveryTime: "14 days",
        features: ["20 Hours of Assistance", "Premium Support"],
        revisionType: "Unlimited",
      },
      premium: {
        name: "Premium Package",
        price: 599,
        description: "Premium virtual assistant package",
        deliveryTime: "21 days",
        features: ["40 Hours of Assistance", "Priority Support"],
        revisionType: 3,
      },
    },
  },
];
