import Sidebar from "@/components/shared/Sidebar/Sidebar"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <div className="flex gap-10">
      <Sidebar />
      <body className="">
        
        {children}
        
        </body>
    </div>
  )
}
